# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cobot_design_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 80, 231, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 19, 211, 124))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.L1_Value_Box = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.L1_Value_Box.setProperty("value", 1.0)
        self.L1_Value_Box.setObjectName("L1_Value_Box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.L1_Value_Box)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.L2_Value_Box = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.L2_Value_Box.setProperty("value", 1.0)
        self.L2_Value_Box.setObjectName("L2_Value_Box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.L2_Value_Box)
        self.L3_Value_Box = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.L3_Value_Box.setProperty("value", 1.0)
        self.L3_Value_Box.setObjectName("L3_Value_Box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.L3_Value_Box)
        self.L4_Value_Box = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.L4_Value_Box.setProperty("value", 1.0)
        self.L4_Value_Box.setObjectName("L4_Value_Box")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.L4_Value_Box)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 211, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.X_Coord_Value_Box = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.X_Coord_Value_Box.setMinimum(-4.0)
        self.X_Coord_Value_Box.setMaximum(4.0)
        self.X_Coord_Value_Box.setObjectName("X_Coord_Value_Box")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.X_Coord_Value_Box)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.Y_Coord_Value_Box = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.Y_Coord_Value_Box.setMinimum(-4.0)
        self.Y_Coord_Value_Box.setMaximum(4.0)
        self.Y_Coord_Value_Box.setObjectName("Y_Coord_Value_Box")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Y_Coord_Value_Box)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(60, 470, 331, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 321, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.T3_Value_Box = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.T3_Value_Box.setObjectName("T3_Value_Box")
        self.gridLayout.addWidget(self.T3_Value_Box, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.T2_Value_Box = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.T2_Value_Box.setObjectName("T2_Value_Box")
        self.gridLayout.addWidget(self.T2_Value_Box, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.T1_Value_Box = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.T1_Value_Box.setProperty("value", 0.0)
        self.T1_Value_Box.setObjectName("T1_Value_Box")
        self.gridLayout.addWidget(self.T1_Value_Box, 0, 2, 1, 1)
        self.T3_Slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.T3_Slider.setMaximum(9999)
        self.T3_Slider.setSingleStep(100)
        self.T3_Slider.setPageStep(1000)
        self.T3_Slider.setProperty("value", 0)
        self.T3_Slider.setSliderPosition(0)
        self.T3_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.T3_Slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.T3_Slider.setObjectName("T3_Slider")
        self.gridLayout.addWidget(self.T3_Slider, 2, 1, 1, 1)
        self.T2_Slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.T2_Slider.setMaximum(9999)
        self.T2_Slider.setSingleStep(100)
        self.T2_Slider.setPageStep(1000)
        self.T2_Slider.setProperty("value", 0)
        self.T2_Slider.setSliderPosition(0)
        self.T2_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.T2_Slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.T2_Slider.setObjectName("T2_Slider")
        self.gridLayout.addWidget(self.T2_Slider, 1, 1, 1, 1)
        self.T1_Slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.T1_Slider.setMaximum(9999)
        self.T1_Slider.setSingleStep(100)
        self.T1_Slider.setPageStep(1000)
        self.T1_Slider.setProperty("value", 0)
        self.T1_Slider.setSliderPosition(0)
        self.T1_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.T1_Slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.T1_Slider.setObjectName("T1_Slider")
        self.gridLayout.addWidget(self.T1_Slider, 0, 1, 1, 1)
        self.Display_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Display_Button.setGeometry(QtCore.QRect(470, 550, 171, 51))
        self.Display_Button.setObjectName("Display_Button")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 40, 651, 451))
        self.groupBox_4.setObjectName("groupBox_4")
        self.MplWidget = MplWidget(self.groupBox_4)
        self.MplWidget.setGeometry(QtCore.QRect(10, 20, 631, 421))
        self.MplWidget.setObjectName("MplWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.L1_Value_Box, self.L2_Value_Box)
        MainWindow.setTabOrder(self.L2_Value_Box, self.L3_Value_Box)
        MainWindow.setTabOrder(self.L3_Value_Box, self.L4_Value_Box)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COBOT_DESIGN"))
        self.groupBox.setTitle(_translate("MainWindow", "Lengths"))
        self.label.setText(_translate("MainWindow", "L1"))
        self.label_2.setText(_translate("MainWindow", "L2"))
        self.label_3.setText(_translate("MainWindow", "L3"))
        self.label_4.setText(_translate("MainWindow", "L4"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Initial Position"))
        self.label_5.setText(_translate("MainWindow", "X Coordinate"))
        self.label_6.setText(_translate("MainWindow", "Y Coordinate"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Input Variables"))
        self.label_8.setText(_translate("MainWindow", "<p>&theta;2</p>"))
        self.label_10.setText(_translate("MainWindow", "<p>&theta;1</p>"))
        self.label_9.setText(_translate("MainWindow", "<p>&theta;3</p>"))
        self.Display_Button.setText(_translate("MainWindow", "DISPLAY COBOT"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Display"))
from mplwidget import MplWidget
